server:
  port: 2020
spring:
  application:
    name: apigateway
  data:
    mongodb:
      uri: URL TO MONGODB
      database: eshopping
  redis:
    host: redis-demo.lbbdc0.0001.use1.cache.amazonaws.com
    port: 6379
jwt:
  secret: MY-Secret-Key
