server:
  port: 2020
spring:
  application:
    name: apigateway
  data:
    mongodb:
      uri: mongodb://mongouser:mongopass@mycluster076-shard-00-00-duylq.mongodb.net:27017,mycluster076-shard-00-01-duylq.mongodb.net:27017,mycluster076-shard-00-02-duylq.mongodb.net:27017/test?ssl=true&replicaSet=MyCluster076-shard-0&authSource=admin&retryWrites=true&w=majority
      database: eshopping
  redis:
    host: redis-demo.lbbdc0.0001.use1.cache.amazonaws.com
    port: 6379
jwt:
  secret: MY-Secret-Key